config_name: "Module-metal_maps"

maps: [
    [ id: 1 ,
      path:  "/home/liyanx/dist2/metal_data/tianliao_office_new_map/1"
    ]
]

Publish_freq: 1.0
change_map_srv:  "Srv-change-map"
Pts_map_topic:   "Map-pts"
Grid_map_topic:  "Map-grid"
Cost_map_topic:  "Map-cost"

